holgerBerger/hpc-workspace

bin/ws_find

I think that `ws_find` should return an error code when the workspace is not found so that it is easy to detect.

Error on ws not found

---

src/ws_allocate.cpp
src/ws_release.cpp
src/ws_restore.cpp
testing/tests/06-parameters/err1.ref

Error message currently reads
> Error: Illegal workspace name, use characters and numbers, -,. and - only!
From the regular expression used I suppose that one of the dashes ( - ) should be an underscore ( _ ).
This pull request changes the error message to
> Error: Illegal workspace name, use characters and numbers, -,. and _ only!

Replace one - with _ in 'Illegal workspace name' error message

---

bin/ws_send_ical

I think it is better to use explicit python3. (/usr/bin/python -> /usr/bin/python3)
Some syntax that is changed in python3 will be corrected if you merge this pull request.
I created this pull request separate from the first one.

use python3

---

sbin/ws_expirer

Without the apostrophe the try statement always throw the exception.

fix to get sender from configuration file

---

CMakeLists.txt
src/ws_allocate.cpp
src/ws_release.cpp
src/ws_restore.cpp

The git commit hash is printed as version number.
If the source is not a git repository then the version number output is empty.
The current commit checks if the subdirectory '.git' exists and acts appropriate the two situations.
The variable IS_GIT_REPOSITORY is set for further use that may be done in the future.

fix empty version number output by using the version option at the release

---

CMakeLists.txt
src/ws_allocate.cpp
src/ws_release.cpp
src/ws_restore.cpp

The output from the version option by a build form the git sources will than look like:
- $ ./bin/ws_allocate -V
workspace build from git commit hash 4c04243 on top of release 1.1.0
The version definition is more on the top of the file `CMakeLists.txt` and is so easier to increase before you publish a new release.
This means that this definition goes to line 4
- add_definitions("-DWS_VERSION=\"1.1.0\"")
and needed to be increased appropriate to each release version.

change the output from the version option

---

testing/scripts/cleanup_tests.sh
testing/scripts/prepare_tests.sh

The commands useradd, groupadd, userdel and groupdel should be available on every unix system, while adduser and co are not.

Testing: Improve portablity

---

src/ws_allocate.cpp

This should protect the user to specify this email address without the option -r. Otherwise he may think he get an email but there will no email be send.

prevent to use -m without -r

---

src/ws.cpp
src/ws_allocate.cpp
src/ws_restore.cpp
src/wsdb.cpp

This series of commits includes
- Removing duplicate headers
- make use of YAML::as default values instead of current try catch semantics
- Fixes compiler warnings related to E.15 cpp core guidelines
- removes duplicate function invocation

Minor code improvement and cleanup

---

src/ws.cpp
src/ws_restore.cpp

Hi,
this just adds, two `exit` calls to avoid a possible Null-pointer de-reference.

Avoid possible Null-Pointer dereference

---

bin/ws_extend

This is a fix for #63
* The ws_extend script was lacking proper quotation of arguments.
* Also changed interpreter from bash to pure shell as there is no need.

Fix ws_extend error when called without arguments

---

src/ws.cpp

* Use real group id instead of effective one as executables may be installed owned by group root have setgid attribute set.

Fix wrong primary group assignment in Workspace::validate

---

CMakeLists.txt

Since there is some C++ code using `auto`, we need to compile using C++11.

Add -std=c++11 to CXX flags

---

bin/ws_share

Users often want to give other users, e.g., support staff, read access to
their workspaces.  Often these users are not in the same user group as the
owner of the workspace. So the only way with standard UNIX perms is to grant
read access for other, which may be critical for some users.
A solution therefore is to use ACLs. However the understanding and correct
usage of ACLs is not easy.
The new ws_share command allows to easily grant and remove read access for
other users as well as list users that were granted access to a workspace.
The ws_share command will perform the necessary command to modify the ACLs
transparently for the user.

Add ws_share to easily manage read access for other users to a workspace

---

sbin/ws_expirer
ws.conf
ws.conf_full_sample

On very large workspaces (and or remote storages) the deletion of workspaces could take several hours or days.
If the ws_expirer process is hanging over this long time, it could happen that on next run, workspaces will expire but the user have not been notified.
To prevent such corner case, we have implemented a user-defined threshold for ws_expirer (per workspace).

add Timeout for ws_expirer

---

contribs/completion/ws_tools.sh

The bash_completion for ws_restore displayed beside the names of
recoverable workspaces also file system names. This was caused, by the
helper function _ws_restore_list including filesystem headings from
the output of `ws_restore -l -b`.
Fixed for now by filtering out entries ending with a colon.

Fix bash_completion for ws_restore

---

sbin/ws_expirer
src/ws_allocate.cpp

ws_allocate
- improve checking of mailaddress characters
- add "reminderdefault" in commandline parsing, to ensure default value, even if no user-specific configuration file is available. This prevent creating workspaces accidentally without mailadress (if using only global reminderdefault value)

BugFixes: ws_allocate

---

sbin/ws_expirer

This commit adds time zone information to the ws_expirer email.
We have a cluster with users across different time zones and want to ensure that the email sent to users isn't misleading for users with respect to when their files will be deleted.

sbin/ws_expirer: Add time zone information

---

CMakeLists.txt

manpages were moved to man/man1, but CMakeLists.txt wasn't updated to reflect this.

Update manpage paths for install

---

CMakeLists.txt

The compiler options did not fit the expectations from the default cmake build types and could not be modified via environment variables. Also some of the used compiler options were gcc specific. The problem came from the fixed assignments to the CMAKE_*_FLAGS_* variables.
- Replaced the fixed assignments with corresponding add_*_options for compiler and linker options that allow to use, e.g., the CXXFLAGS environment variable, to pass additional options.
- Removed (gcc-specific) compiler options for suppression of some warnings
- Used cmake generator expressions to add "Release"/"MinSizeRel" specific options
- Pass the symbol striping option to the linker instead of to the compiler

Improve cmake compiler/linker flag handling for build targets

---

admin-guide.md
sbin/ws_validate_config
src/ws.cpp
ws.conf_full_sample

When adding a new space to an existing workspace, the existing algorithms will still try to split allocations evenly. Adding this option gives the ability to prefer the space with the most available room instead.

Add an option to chose space by most free bytes

---

contribs/schemas/hpc-workspace-config-v1_5.json

An initial version of a json schema file for the YAML configuration file based on json-schema version 'draft-07' (see https://json-schema.org). This can be used for configuration validation and auto-completion.

Provide initial json schema for YAML config file

---

sbin/ws_expirer

ws_expirer: add option for running on storage targets only
