holgerBerger/hpc-workspace

admin-guide.md

mostly typos and grammar corrections

proof reading of admin-guide.md

---

CMakeLists.txt
bin/ws_send_ical

I would be nice to can 'make install'.

get the target "install" for make

---

admin-guide.md
bin/ws_find

- wrapped at 80 charaters
- wrong newlines removed

add documention to run ws_expirer as cronjob

---

sbin/ws_expirer

Make ws_expirer a bit more robust

---

bin/ws_list

... handle it by not crashing and furthermore printing a hint to stderr.
And my vim configuration removed a lot of trailing whitespaces ;-)

Check for empty workspace database entries

---

contribs/completion/ws_tools.sh

Basic bash completion for ws_list, ws_find, ws_extend, ws_remove. Expands
options, file systems and workspace names.

Provide basic bash completion functionality

---

contribs/completion/ws_tools.sh

Added bash completion for the ws_restore command following the built in help

Add bash completion for ws_restore

---

src/ws.cpp

Exit on cap_X or Xeuid errors

---

src/ws_allocate.cpp

With the little change now this should also pass the tests.

add option check again that now will pass the tests

---

admin-guide.md

Fix typos in admin documentation

---

src/ws.cpp

* Fix wrong argument that may allow validation bypassing
* Fix return value check

Fix issues around getgrouplist in Workspace::validate

---

bin/ws_register

- General code cleanup
- Fix typo in functionname
- Improve message outputs
- Fix errors from missing parent directories
- Fix usage message and switch from optparse to argparse + use of pathlib

Some fixes and cleanup for ws register

---

contribs/completion/ws_tools.sh

Add bash completion for the newly added ws_share.
Completes file systems, workspace names, system users, and users granted access to a workspace.
Note: The completion does not check for duplicate user names

Add bash completion for ws_share

---

user-guide.md

Improve and fix typos in the User Guide

---

sbin/ws_expirer

* Fix recursion in slowdeldir
* Fix incorrect usage of format() in debug output
@holgerBerger Please note that changes in this critical part were not tested by me in a real setup and should be reviewed/tested!

Some fixes for the ws expirer

---

man/ws_share.1

Add man page for ws_share

---

testing/rockylinux8/Vagrantfile

Add vagrant configuration for testing with Rocky Linux 8

---

bin/ws_share

Fix long option parsing of ws_share command

---

bin/ws_find
bin/ws_register
bin/ws_send_ical
sbin/ws_restore

Remove unused imports

---

CMakeLists.txt

Add ws_share to the list of files to install.

Install ws_share

---

admin-guide.md
bin/ws_find
bin/ws_list
bin/ws_register
bin/ws_send_ical
contribs/ws_prepare
pyproject.toml
sbin/ws_expirer
sbin/ws_restore
sbin/ws_validate_config

This pull request adds linting for python files.
This is the basis for the next pull request, so there is no clutter caused by formatting changes.

Add Linting for Python

---

bin/ws_find
bin/ws_register
bin/ws_send_ical
getyamlcpp.sh
sbin/ws_expirer
src/ws.cpp
src/wsdb.cpp

Improvements from use on CARA:
* ws_expirer:
* extended error handling
* logging via logging and not prints
* collecting and printing stats
* minor code improvements
* more expressive reminder mail
This contains the 2 commits from #105 , which may be bad form?

Cara improvements

---

ws.conf_full_sample

- Use spaces instead of tabs (rationale: https://yaml.org/faq.html)
- Align comments
- Fix spelling

Polish ws.conf_full_sample

---

sbin/ws_expirer

- Add filesystem to mail. This might help the users to figure out, what workspace is expiring. A user can have workspaces with identical names on all workspace directories of the very same HPC system.
- Remove comments; Seems to be a left over from development

Review send_mail function
